# docker-compose.yml
# https://medium.com/analytics-vidhya/getting-started-with-postgresql-using-docker-compose-34d6b808c47c
version: '3.8'

volumes:
  psql-data:

networks:
  default:
    name: cloudbuild
  openicecat-etl-db-net:


services:

  db:
    image: postgres:12 # use latest official postgres version
    container_name: openicecat-etl-db
    ports:
#      - HOST:CONTAINER
#      - "5434:5432"
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - database.env # configure postgres
    volumes:
      - psql-data:/var/lib/postgresql/data/pgdata
#    command: postgres -c max_connections=300 -c shared_buffers=1536MB -c effective_cache_size=4608MB -c maintenance_work_mem=384MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=2621kB -c min_wal_size=2GB -c max_wal_size=8GB -c max_worker_processes=4 -c max_parallel_workers_per_gather=2 -c max_parallel_maintenance_workers=2 -c max_parallel_workers=4 -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
#    command: postgres -c max_connections=200 -c shared_buffers=4096MB -c effective_cache_size=12288MB -c maintenance_work_mem=1024MB -c checkpoint_completion_target=0.9 -c wal_buffers=16MB -c default_statistics_target=100 -c random_page_cost=1.1 -c effective_io_concurrency=200 -c work_mem=10485kB -c min_wal_size=1GB -c max_wal_size=4GB -c max_worker_processes=4 -c max_parallel_workers_per_gather=2 -c max_parallel_maintenance_workers=2 -c max_parallel_workers=4 -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
#    command: postgres -c shared_preload_libraries='pg_stat_statements' -c pg_stat_statements.track=all
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      openicecat-etl-db-net:

#   pghero:
#     image: ankane/pghero # use latest official postgres version
#     container_name: openicecat-etl-pgHero
#     ports:
#       - "8080:8080"
#     restart: unless-stopped
#     environment:
#       - PGDATA=/var/lib/postgresql/data/pgdata
#      - DATABASE_URL=postgres://unicorn_user:magical_password@openicecat-etl-db:5432/rainbow_database
#      - DATABASE_URL=postgres://unicorn_user:magical_password@openicecat-etl-db:5432/unicorn_database
#     networks:
#       openicecat-etl-db-net:
